### ISSUE TITLE
Google Location accuracy necessary?

### ISSUE THREAD

**Issue by Der-Flip** [Myzel394/locus#7] opened 2023-05-24 10:17 UTC
Hi, I was trying the app, unfortunately locus.app seems to be down currently, but that just on the side.

I was wondering whether Google Location Accuracy is really necessary for this app to work...
I don't need position accuracy while indoors. I'm perfectly fine with just regular gps accuracy like for instance phonetrack (/OwnTrack) and Opentracks are using.
Unfortunately, whenever GLA is disabled not a single position is being acquired. By that I mean, the app doesn't even attempt to retrieve a GPS fix. As soon as i (begrudgingly) enable GLA, though, the app immediately acquires a location fix.

Is there a chance to make GLA and Google Location Services in General optional?

**Comment by Myzel394** [comment] 2023-05-24 11:23
Hey @Der-Flip thanks for opening the issue

> Hi, I was trying the app, unfortunately locus.app seems to be down currently, but that just on the side.

The domain is actually `locus.cfd` - locus.app was already taken :/ I'm currently trying to deploy it. Though it will probably take some days as I'm currently at work

> I was wondering whether Google Location Accuracy is really necessary for this app to work...

I'm currently figuring out what's the best way to get good location accuracy (for those who need it) without Google, @IzzySoft already gave me some tips, which I'll try out.

> Unfortunately, whenever GLA is disabled not a single position is being acquired.

That's a bit strange since it should fall back to location manager on Android if there is no Google available - let me investigate this!

Sorry that I have no quick fix available for you. The app is still in beta, so there might come up some more bugs. Thanks for opening the issue though, this helps me making the app accessible to everyone 😄

**Comment by Myzel394** [comment] 2023-05-24 11:47
> hi, don't worry, I don't rely on it, I was just gonna try it out as a fallback, should I move away from phonetrack / OwnTrack

Not trying to discourage you from using Locus (of course I wouldn't discourage someone from using my apps :D), but Locus is more optimized to be used to share the current location or track your phone. If I'm not mistaken, OwnTrack is meant to act as a replacement for Google's Location History (correct me if I'm wrong). When you use Nostr clients on Locus, there is no guarantee that those relays store your location for a long time (except when you host your own relay). I'm telling that just so that you (or other people reading this) are not sad when their locations are suddenly gone :D

> Redmi9C
Android 10 (QP1A.190711.020)
MIUI Global 12.0.14 Stable (QCREUXM)

I do have a Xioami Device myself, but never knew you could disable Google's Location Accuracy?!? Could you tell me how you did that, that way I can probably replicate your issue more easily.

**Comment by Der-Flip** [comment] 2023-05-24 11:53
> OwnTrack is meant to act as a replacement for Google's Location History

yes and no. There are public session urls you can share and it is being displayed on a map as well, but yes, there is extended functionality to save the tracks as gpx and archive them (i.e. position history). I currently use it mostly for sharing location.

> Could you tell me how you did that

Settings > Location
https://github.com/Myzel394/locus/assets/18213041/4bcb86e2-6883-4610-8f9f-5e14facb0ed2

**Comment by Myzel394** [comment] 2023-05-24 14:24
Okay I have tried some Google-free alternatives now, but unfortunately it seems as if they won't work on MIUI. However, on GrapheneOS they seem to work (with and without Google Services). I think this is a probably an issue with MIUI then. I've had several issues with MIUI in the past already and other developers complained about it too. I personally do not recommending a MIUI-based device at all. Both their terrible Android flavor as well for their bad device support (some devices only get like 2 years of security updates) make Xiaomi phones in my opinion a no-go.
Nevertheless, I'm still a bit confused why your other apps work quite well without Google. I guess Flutter doesn't have much floss packages. When I have some free time available, I think I'll spend some time implementing my own location fetching method without relying on Google.

As for now, your only choice is to either allow Google Location Accuracy or buy a new phone (without MIUI).

For other developers and future reference, here are the packages that I've already tried:

* [Geolocator](https://pub.dev/packages/geolocator) with [libre fork](https://gitlab.com/hanntech-gmbh/free2pass/flutter-geolocator-floss) - Either sometimes still asks for Google Location Accuracy or timeouts
* [gps](https://pub.dev/packages/gps) - Discontinued
* [location](https://pub.dev/packages/location) - Does not work without Google ([see this PR](https://github.com/Lyokone/flutterlocation/issues/582))

Geolocator seems to be the only one that fall backs to location manager (sometimes?) and works on GrapheneOS (even though it needs like 20 seconds or so). That means I'll currently stick with `geolocator`, even though it required GSM, because at least it works on all Android flavors, even if it requires Google.

**Comment by Der-Flip** [comment] 2023-05-24 15:02
> I'm still a bit confused why your other apps work quite well without Google.

can't say really. GPSLogger, GPS Logger (with a space, different app), Opentracks, GPS Cockpit, Windy, Organic Maps, Street Complete, Magic Earth and other gps apps work well, but I've encountered a few apps now, that don't, most of these began development rather recently

As for the MIUI device. while it was supposed to be a temporary phone 2 years back which I needed same day (I forgot blackberry stopped working Jan 4 2021 which is why I went for the absolute cheapest I could get by walking into a store without a phone and out of the store with a phone) it has become a bit of a semi permanent phone now, as my financial situation ain't exactly the best currently, so I need to stick with it for now. It ain't a device I would necessarily recommend and I do have encountered some issues as well (apps just quitting despite them being exempt from all battery saving measures) and I did see MIUI ain't very popular with the devs (I can see why).... since I really rely on this phone though, I don't have the guts to just wipe and put on whatever OS i like^^

As with many other apps, I'll just keep this one around, keep updating it, and maybe it just decides to work at some point :P

Appreciate the effort though!

**Comment by Myzel394** [comment] 2023-05-24 15:35
> GPSLogger, GPS Logger (with a space, different app), Opentracks, GPS Cockpit, Windy, Organic Maps, Street Complete, Magic Earth

I think all (or at least most of them) are fully native apps (written in either Java or Kotlin), meaning that they can directly access Android. Locus however is written in Dart / Flutter, meaning that we can't access Android so directly. We do can access it, but we'll first need to add bridges for that and it's all a bit fiddly. Like I said, I will definitely look into that when I have some free time though. Luckily for me, all those apps you mentioned are open source, so I have plenty of resources to look at :D

I'll close this issue for now, but once I manage to add the bridge to Android and use the location without any Google, I'll ping you and then hopefully everyone can use the app. I'm very sorry for the inconveniences.

**Closed by Myzel394** 2023-05-24 15:35 UTC
Labels: bug

**Comment by IzzySoft** [comment] 2023-05-24 17:51
Just adding my 2 cent here: Nice to see the overlap in the app list. Remember I've brought some of them to your attention earlier, @Myzel394? So adding on top of those: Tower Collector, Every Door. As most of them are available on F-Droid, they are fully FLOSS (no GSM libs included).

So would you go with the [FLOSS fork of Geolocator](https://gitlab.com/free2pass/flutter-geolocator-floss) then, which I pointed to before (and which you tried now)? That btw originated with the [inclusion of LibreHealth](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7908#note_475817115) at F-Droid – which, you might have guessed it, is a Flutter app. Also see the notes on this one at the end of [my snippet](https://gitlab.com/-/snippets/1896503).

> I think all (or at least most of them) are fully native apps (written in either Java or Kotlin)

Let's check:

* [Tower Collector](https://github.com/zamojski/TowerCollector): Java
* --> **[Every Door](https://github.com/Zverik/every_door): Flutter** <--
* [GPSLogger](https://github.com/mendhak/gpslogger): Java
* GPS Logger: ?
* [OpenTracks](https://github.com/OpenTracksApp/OpenTracks): Java
* [GPS Cockpit](https://github.com/woheller69/gpscockpit): Java
* Windy: ?
* [Organic Maps](https://github.com/organicmaps/organicmaps): C++
* [Street Complete](https://github.com/streetcomplete/StreetComplete): Kotlin
* Magic Earth: ?

So yes, most – but not all. Maybe you want to have a look how Every Door tackled it? Never had any location issues with that app. But I have to admit that, almost ever I do something that needs location, I have Tower Collector running in the background (why not do something useful for the community at the same time if it takes close to no additional efforts, after all).

**Comment by Myzel394** [comment] 2023-05-24 17:58
> So would you go with the [FLOSS fork of Geolocator](https://gitlab.com/free2pass/flutter-geolocator-floss) then, which I pointed to before (and which you tried now)?

I know it's not great but I'll stick to the google based geolocator since the FLOSS variant doesn't seem to work on google devices :/

Every Door uses `geolocator` (https://github.com/Zverik/every_door/blob/main/pubspec.yaml#L19) - I have no idea what black magic is going on there that it somehow doesn't use google :O Will take a closer look at the app later

**Comment by IzzySoft** [comment] 2023-05-24 18:40
> but I'll stick to the google based geolocator since the FLOSS variant doesn't seem to work on google devices

The term "build flavor" comes to mind…

> I have no idea what black magic is going on there

I've checked the YAML in F-Droid's metadata, suspecting some `sed` magic – but couldn't spot any related (there is some `sed`, but not for geolocator). The only ones I see are:

```yaml
      - sed -i -e 's/^#f//' pubspec.yaml
      - sed -i -e 's/^\(.*\bMultiDex\b\)/\/\/ \1/' android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java
      - echo '{}' > lib/l10n/app_zh.arb
      - export PUB_CACHE=$(pwd)/.pub-cache
      - vendor/flutter/bin/flutter config --no-analytics
      - vendor/flutter/bin/flutter packages pub get
```

So if there's some geolocator magic, it must indeed be in the app's repo itself.

Ha! Yes, combination. It's the first `sed` working on [these lines](https://github.com/Zverik/every_door/blob/aaf8d2fdeac483041bcac2c7c79ef760b99dff2b/pubspec.yaml#L55), making it use a modified geolocator just for the F-Droid build. So: back to "build flavor" I guess?

```yaml
# Uncomment this for publishing on F-Droid
#fdependency_overrides:
#f  geolocator_android:
#f    git:
#f      url: https://github.com/Zverik/flutter-geolocator.git
#f      ref: floss
#f      path: geolocator_android
```

**Comment by Myzel394** [comment] 2023-05-24 18:57
> # Uncomment this for publishing on F-Droid
#fdependency_overrides:
#f  geolocator_android:
#f    git:
#f      url: https://github.com/Zverik/flutter-geolocator.git
#f      ref: floss
#f      path: geolocator_android

Oh lol I have skillfully read over that xD

> back to "build flavor" I guess?

I haven't used build flavors yet but if I understand the docs correctly, they are basically different versions of the app (according to https://developer.android.com/build/build-variants), which means that we would for example use the FLOSS geolocator on F-Droid and the proprietary one on the Google Play Store. The problem with that however, is, that some people still use Android with Google Services (like @Der-Flip) - meaning that the app won't work at all for them.

However, I'm not sure if this is a MIUI-specific issue. I'm going to buy a Samsung phone to see if the geolocator there. @IzzySoft do you know if there is a way to use flavors for specific flavors of Android (Stock, MIUI, Samsung One UI etc.)? If yes, we could maybe do that and for example use the proprietary geolocator on MIUI and the Stock ROM, and use the FLOSS geolocator on other devices by default (meaning that for example GrapheneOS, LineageOS etc. all use the FLOSS variant)

**Comment by IzzySoft** [comment] 2023-05-24 19:32
> Oh lol I have skillfully read over that xD

:rofl: Yeah, some unimportant comments – if one doesn't have the counter-part from fdroiddata :see_no_evil:

> they are basically different versions of the app

Yupp. I've no idea with Flutter, but with gradle you can basically say e.g. `fossImplementation` and `gplayImplementation` for flavor-specific stuff, and keep those for both flavors as `implementation`; then wen you build the foss flavor, the `gplayImplementation` stuff would be skipped.

> which means that we would for example use the FLOSS geolocator on F-Droid and the proprietary one on the Google Play Store

That was the idea, yes. Then have the APKs of both flavors attached to the release, and folks can choose.

> a way to use flavors for specific flavors of Android

You could define such – but I have no idea how to make them automatically applied to the corresponding devices. Basically, each flavor would mean its own APK (app-bundles apart), so how make the device choose? One way would be using specific `applicationId`s for each and have the description giving a proper hint. But then, what if you decommission your MII and get yourself a Samsung, how would you switch to the other variant without losing your data? If you want to follow that path, make sur to have a proper migration path (e.g. export/import functionality, so one can export data from one and import it to the other flavor). I'd then pick the foss flavor for my repo – and there could be a note in the app description giving a proper hint for MIAU, err, MIUI folks. And maybe keep the current `applicationId` for the foss variant (so we don't have to switch things around in my repo), giving the other one an appended `.gms` or so.

Alternatively, keep the same `applicationId` for both and just name the APK files differently at `releases/` so I know which one to pick, then ship the GMS one to Google (those using that walled garden will have GMS on their devices anyway, in most cases; if they rather use Aurora Store, they can cross-update "choice-wise" :wink:

**Comment by Myzel394** [comment] 2023-05-24 19:51
@IzzySoft let's continue this on #10

**Comment by Der-Flip** [comment] 2023-05-28 10:50
just wanna let you know (although you probably already do) location works now without Google Location Accuracy :)

**Comment by Myzel394** [comment] 2023-05-28 11:26
@Der-Flip wait what?!???? It didn't work for me on my Xiaomi device but I'm glad it does work for you! :O What variant do you use, FLOSS or GMS?

**Comment by Der-Flip** [comment] 2023-05-28 11:46
not sure to be honest... 0.2.2 on izzy FDroid repo...

on that note: probably adding a version info in settings>support Locus section would be good^^

**Comment by Myzel394** [comment] 2023-05-28 12:30
> settings>support Locus section would be good^

Agree, I will add that. Especially because version 0.2.2 shouldn't exist :sweat_smile: I think you are on 0.3.1, but I'm not sure either at this point. I definitely need to add that version number to the settings :D

**Comment by IzzySoft** [comment] 2023-05-28 18:43
> Agree, I will add that. Especially because version 0.2.2 shouldn't exist sweat_smile I think you are on 0.3.1

You forgot that v0.3.0 went online in my repo as v0.2.2 during the tagging mess :wink:

**Comment by Myzel394** [comment] 2023-05-28 18:45
@IzzySoft oh okay, the newest version should be 0.3.2 now, so we don't need to take care of 0.2.2 / 0.3.0  anymore :D

**Comment by Der-Flip** [comment] 2023-05-28 20:17
I do regret to inform you that 0.3.1 stopped working from 0.2.2 😳😂

no Google Accuracy prompt, but no fix retrieval either...

**Comment by Myzel394** [comment] 2023-05-28 20:29
@Der-Flip you will need to install the GMS version on MIUI, since you have Google Play Services installed :/

**Comment by Der-Flip** [comment] 2023-05-28 23:00
makes sense....

now, uhm... not sure how to say this, but it does seem to work now without me having changed anything...😳 I'll keep an eye on it^^

**Comment by Myzel394** [comment] 2023-05-29 09:19
@Der-Flip do you mean the FLOSS variant works now without Google Location Accuracy?

**Comment by Myzel394** [comment] 2023-06-05 18:08
@IzzySoft I have created another PR to remove GMS and NOW GMS should finally be completely removed in the FLOSS version :sweat_smile: Can you confirm it's gone now?

**Comment by IzzySoft** [comment] 2023-06-05 20:27
That was just missed by my updater by half an hour :see_no_evil: Triggering a manual update now… through. And yes, confirmed :partying_face: AF removed again :smiley:

**Comment by Myzel394** [comment] 2023-06-05 20:29
@IzzySoft Thanks for the manual update! :D Hopefully Google will now stay out of the FLOSS version once and for all

**Comment by IzzySoft** [comment] 2023-06-05 20:51
So do I! Oh, and the update goes live with the next sync of course, it was just pulled to my staging area now. But you certainly know that procedure meanwhile :see_no_evil:
