### ISSUE TITLE
[BUG] Location not updating in background

### ISSUE THREAD

**Issue by mrdanleey** [Myzel394/locus#76] opened 2023-07-03 09:39 UTC
## OS

* [x] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [x] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [x] LineageOS

## Describe the bug
I installed Locus on 3 mobile phones:

2 are from Samsung with Android 11 and 13 (installed the GMS version)
1 mobile phone had E/OS (LineageOS based rom) (installed the FOSS version).

I found that the app won't work in the background, I see the notification and the app is active, but it isns't updating
the location at all. I do not see any location updates in the app.

## Priority
Please set a realistic priority on how important this issue is to you. We will fix all bugs, but urgent bugs (such as the app not starting at all for example) are more important than fixing some styles for example.

* [ ] Low
* [x] Medium
* [ ] High
* [ ] Urgent
 
## App Version
Version 0.11.1 (GMS)" and "Version 0.11.1 (FLOSS)".
Also tried older versions like 0.10.2 and 0.10.3

**Comment by Myzel394** [comment] 2023-07-03 09:43
Hey @mrdanleey,

can you try doing a location check in Locus? You can do so by opening the app, tapping on settings (top right gear icon) > "Verify location access" and then start the check.

**Comment by mrdanleey** [comment] 2023-07-03 10:55
Verify location access works and shows my location

**Comment by Myzel394** [comment] 2023-07-03 11:01
@mrdanleey okay that's good. Do you have an active task running?

**Comment by Myzel394** [comment] 2023-07-03 12:50
Is Locus open (aka _not_ swiped away)? Otherwise, could you try disabling battery optimizations? Also, could you share your logs?

**Comment by mrdanleey** [comment] 2023-07-03 15:33
Locus is open indeed, I disabled every battery optimization, but could not find Locus in the list with apps I can select that my mobile's may not close forever. I will share my logs this evening with you

**Comment by mrdanleey** [comment] 2023-07-04 06:54
Hereby the logfiles from my Samsung mobile and the one with E/OS (LineagenOS based mobile)

[04072023_070643_AM_all_[21].zip](https://github.com/Myzel394/locus/files/11945653/04072023_070643_AM_all_.21.zip)
[04072023_071905_AM_all_[74].zip](https://github.com/Myzel394/locus/files/11945654/04072023_071905_AM_all_.74.zip)

**Comment by Myzel394** [comment] 2023-07-06 19:56
@mrdanleey sorry for the late response. I finally found the time to look at this. So the good news is: Background tasks do work. There is either a problem with Locus itself, or with background location fetching. Can you confirm you have allowed access to your location all the time?

Ohhh btw I just noticed the following:

> > Do you have an active task running?

> 
Yes I have a permanent notification that says Locus is running


By "task" I meant a location share task. On the overview you can enable and disable them. Please make sure you have one running.

Here's a screenshot of an example overview:

![20230706_215527_temp](https://github.com/Myzel394/locus/assets/50424412/583318a3-4172-4274-855a-9debfd5ed343)

**Comment by mrdanleey** [comment] 2023-07-07 07:16
Yes I have a running task like your screenshot.

**Comment by Myzel394** [comment] 2023-07-07 19:55
@mrdanleey Can you try it again with the newest version (0.11.2)? Please let Locus at least run 1 hour in the background to allow it trying to fetching the location in the background at least once. If it still doesn't work, please send the new logs again. I have added more logging in the new release which will allow me to investigate your case in more detail. :D

**Comment by mrdanleey** [comment] 2023-07-10 14:06
It's working now, location updates are send in the background. :-)

But now i have the question if it is possible to start the app as a service so you can not close it when swiping the notification away.

**Comment by Myzel394** [comment] 2023-07-10 14:27
> But now i have the question if it is possible to start the app as a service so you can not close it when swiping the notification away.

Locus should work in the background too, even if you swipe the app away.

**Comment by mrdanleey** [comment] 2023-07-11 07:08
> > But now i have the question if it is possible to start the app as a service so you can not close it when swiping the notification away.
> 
> Locus should work in the background too, even if you swipe the app away.

I have swiped the app away and see no location updates on my phones, only when I open the app again or not swiping the notificaton away. I can confirm that the app is running in the background after swiping it away though.

[11072023_090413_AM_all_[196].zip](https://github.com/Myzel394/locus/files/12011657/11072023_090413_AM_all_.196.zip)

**Comment by Myzel394** [comment] 2023-07-11 07:13
> I can confirm that the app is running in the background after swiping it away though.

If that's the case, Locus should update the location in the background. The notification is only shown if the app is opened.

**Comment by mrdanleey** [comment] 2023-07-11 18:29
> > I can confirm that the app is running in the background after swiping it away though.
> 
> If that's the case, Locus should update the location in the background. The notification is only shown if the app is opened.

But it doesn't update when in the background and notification swiped away. I see no updates

**Comment by Myzel394** [comment] 2023-07-11 18:34
Okay that's strange, could you share your logs again? I can't unzip your first zip file

**Comment by mrdanleey** [comment] 2023-07-11 18:42
I tried to export the logs again but I can't extract it too. It looks like the exported logfile is 0 kb and the zip-file is corrupt.

**Comment by Myzel394** [comment] 2023-07-11 18:43
On what version can't you export the logs? GMS or FLOSS?

**Comment by mrdanleey** [comment] 2023-07-11 18:50
Both versions

**Comment by Myzel394** [comment] 2023-07-11 18:53
Hmmm... I guess it has to do something with LineageOS, because (unfortunately) it works for me on GrapheneOS. I'm going to release a new version in the coming days, is it okay for you to wait for the release and then see if the issue still persists?

**Comment by mrdanleey** [comment] 2023-07-16 14:46
I like the maps view, but whrn i check the location of a share and click on another share, the location of the first share is not replaced in the botom part of the screen.
‐--------------

I tried the lication sharing in the background and had some strange things. One of the deleted shares came back after openibg the all shares section again. I decided to install Locus on my mobiles fresh to give it a clean start. Now ckecking the location updates in the backgtound

**Comment by mrdanleey** [comment] 2023-07-16 16:02
[16072023_175819_PM_all_[2].zip](https://github.com/Myzel394/locus/files/12064498/16072023_175819_PM_all_.2.zip)

Location Sharing in the background still not working...

**Comment by Myzel394** [comment] 2023-07-16 16:05
Thanks for the logs @mrdanleey, it seems as if Locus has trouble fetching your location, can you confirm that a manual location update works (Open the sheet and tap on "Update Location now")?

> One of the deleted shares came back after openibg the all shares section again

I'm not sure what you mean by that, can you explain this a bit more?

**Comment by mrdanleey** [comment] 2023-07-16 16:08
The location fetching is working, but only when app is in the foreground. Tried both versions.

I had a sharelink from another phone to show his location  that I deleted. But everytime I deleted it, it came back in my list. But that is solved by reïnstalling Locus.

Can you see in thevlifs why I have problrms get my locstion in the background?

**Comment by Myzel394** [comment] 2023-07-16 16:16
> I had a sharelink from another phone to show his location that I deleted. But everytime I deleted it, it came back in my list. But that is solved by reïnstalling Locus.

Okay I will take a look at that.

> Can you see in thevlifs why I have problrms get my locstion in the background? All my 3 phones having it.

Unfortunately not, the logs actually say that a location has been successfully shared in the background at 05:58:14, there rather seems to be an issue with the decryption process, I'm taking a look at this now.

**Comment by mrdanleey** [comment] 2023-07-16 16:20
> > I had a sharelink from another phone to show his location that I deleted. But everytime I deleted it, it came back in my list. But that is solved by reïnstalling Locus.
> 
> Okay I will take a look at that.
> 
> > Can you see in thevlifs why I have problrms get my locstion in the background? All my 3 phones having it.
> 
> Unfortunately not, the logs actually say that a location has been successfully shared in the background at 17:58:14 (your time), there rather seems to be an issue with the decryption process, I'm taking a look at this now.

Thanks! For the record, at 17:58 i had the app running in the foreground. From 17:08 till 17:58 it was in the background and gave no location updates

**Comment by Titaniumtown** [comment] 2023-07-16 16:48
I can also reproduce this bug. hoping to move off life360, hope this can be fixed!

**Comment by Myzel394** [comment] 2023-07-16 16:55
> I can also reproduce this bug. hoping to move off life360, hope this can be fixed!

What OS are you using? Unfortunately I can not reproduce this bug yet, but I'm trying my best to fix it anyway :D

**Comment by Titaniumtown** [comment] 2023-07-16 16:56
lineageos on my pixel 7

**Comment by Myzel394** [comment] 2023-07-16 16:58
@Titaniumtown can you confirm that Locus can access your location? You can do that by tapping on the bottom right icon > Settings > Verify location access > Start check

**Comment by Titaniumtown** [comment] 2023-07-16 17:00
I tried that, in the foreground location detection works, even when it's not the focused app, but when the phone is asleep, no location data is sent.

**Comment by Titaniumtown** [comment] 2023-07-16 17:03
I am unable to find any settings that could affect this on my device, Locus is granted unrestricted battery access on my phone.

**Comment by Myzel394** [comment] 2023-07-16 17:04
Okay seems as if this is related to LineageOS because (unfortunately) it works for me on GrapheneOS. I currently do not have a LineageOS based phone but maybe I can get access to one in the near future, I'll still try to find the bug blindly and publish updates - if it someday magically works, please let me know

**Comment by Titaniumtown** [comment] 2023-07-16 17:07
Thank you. I do have something to add. I am able to confirm that on a OnePlus 8 pro running the stock rom and gms, Locus background location detection works without issues. Unfortunately Android app development is not my area of expertise so I don't have much more to add.

**Comment by Myzel394** [comment] 2023-07-16 17:24
@Titaniumtown how long did it take for Locus to get your location when you did the check? Also thank you very much for the sponsor! Very much appreciated! :=)

**Comment by mrdanleey** [comment] 2023-07-16 17:25
> Okay seems as if this is related to LineageOS because (unfortunately) it works for me on GrapheneOS. I currently do not have a LineageOS based phone but maybe I can get access to one in the near future, I'll still try to find the bug blindly and publish updates - if it someday magically works, please let me know

I got on on both Samsung stock and one LineageOS phone. So it's not only LineageOS.

**Comment by Titaniumtown** [comment] 2023-07-16 17:30
> @Titaniumtown how long did it take for Locus to get your location when you did the check?

Very quick, maybe like 10 seconds it felt like.

> Also thank you very much for the sponsor! Very much appreciated! :=)

No problem! Hope to see this project improve!

**Comment by Myzel394** [comment] 2023-07-16 17:32
> Very quick, maybe like 10 seconds it felt like.

Okay that's... kinda strange in a positive way. Could you share your logs with me?

**Comment by Titaniumtown** [comment] 2023-07-16 17:32
Do they contain personally identifying information?

**Comment by Myzel394** [comment] 2023-07-16 17:51
@Titaniumtown nope, I specifically designed the logs so that they do not contain anything that can be linked to you. Location requests for example only log whether a location request was successfull or not, but not what location was fetched. The only value that is written to the logs that may be of concern are the nostr relays. This is done so that I can more easily distinguish between them and also see if for example a Nostr relay is down, requires payment or to simply reproduce the issue with the exact relay.

Here's for example an excerpt from fetching a location:

```
{LocusLog}  {Headless Task; Update Location}  {Everything restored, now checking for running tasks.}  {16 July 2023 05:52:24 PM}  {INFO}
{LocusLog}  {Headless Task; Update Location}  {Fetching position now...}  {16 July 2023 05:52:24 PM}  {INFO}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.best}  {16 July 2023 05:52:24 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.best: TimeoutException after 0:00:05.000000: Future not completed}  {16 July 2023 05:52:29 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.worst}  {16 July 2023 05:52:29 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.worst: TimeoutException after 0:00:05.000000: Future not completed}  {16 July 2023 05:52:34 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.androidLocationManagerBest}  {16 July 2023 05:52:34 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.androidLocationManagerBest: TimeoutException after 0:00:05.000000: Future not completed}  {16 July 2023 05:52:39 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.androidLocationManagerWorst}  {16 July 2023 05:52:39 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.worst: TimeoutException after 0:01:00.000000: Future not completed}  {16 July 2023 05:52:43 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.androidLocationManagerBest}  {16 July 2023 05:52:43 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.androidLocationManagerWorst: TimeoutException after 0:00:05.000000: Future not completed}  {16 July 2023 05:52:44 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.best}  {16 July 2023 05:52:44 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.androidLocationManagerWorst: TimeoutException after 0:01:00.000000: Future not completed}  {16 July 2023 05:52:47 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.best}  {16 July 2023 05:52:47 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.androidLocationManagerBest: TimeoutException after 0:01:00.000000: Future not completed}  {16 July 2023 05:57:02 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.androidLocationManagerWorst}  {16 July 2023 05:57:02 PM}  {INFO}
{LocusLog}  {Get Location}  {Error getting location using method LocationMethod.best: TimeoutException after 0:01:00.000000: Future not completed}  {16 July 2023 05:57:13 PM}  {ERROR}
{LocusLog}  {Get Location}  {Getting location using method: LocationMethod.worst}  {16 July 2023 05:57:13 PM}  {INFO}
{LocusLog}  {Headless Task; Update Location}  {Fetching position now... Done!}  {16 July 2023 05:58:08 PM}  {INFO}
{LocusLog}  {Headless Task; Update Location}  {Fetching position now... Done!}  {16 July 2023 05:58:08 PM}  {INFO}
{LocusLog}  {Headless Task; Update Location}  {Publishing position to 1 tasks...}  {16 July 2023 05:58:08 PM}  {INFO}
{LocusLog}  {Headless Task; Update Location}  {Publishing position to 1 tasks...}  {16 July 2023 05:58:08 PM}  {INFO}
```

**Comment by Titaniumtown** [comment] 2023-07-16 17:58
@Myzel394 ok great! I was skimming through my logs to make sure. Here's my logs then:
[16072023_195106_PM_all_[16].zip](https://github.com/Myzel394/locus/files/12064722/16072023_195106_PM_all_.16.zip)

Should contain the relevant times in which issues occured

**Comment by Myzel394** [comment] 2023-07-17 16:26
Okay guys I have released a new version `0.12.1` which should fix this issue hopefully. IzzyOnDroid will sync it in approximately 23 hours, you can either wait for this sync or manually install it from GitHub https://github.com/Myzel394/locus/releases

**Comment by Titaniumtown** [comment] 2023-07-17 16:53
@Myzel394 Fantastic! I'll report back if it fixes it for me or not

**Comment by mrdanleey** [comment] 2023-07-19 16:50
@Myzel394 I installed the new update en begun testing it. It now shared the location on the background approx. every 15 minutes. So that's great! Sometimes it does not refresh the location from the other mobile but refresh when I'm moving Locus to te background en open it again. But overall I'm happy that it is working now.

One thing I notice is that when I'm on the map and clicking the first phone I'm following and than clicking on the 2nd phone I'm following the name refreshed but the location (text only, marker on the map is on the right place) not.

**Comment by Titaniumtown** [comment] 2023-07-19 16:58
Background location logging works well for me

**Comment by Myzel394** [comment] 2023-07-19 17:13
That's great to hear! 

> One thing I notice is that when I'm on the map and clicking the first phone I'm following and than clicking on the 2nd phone I'm following the name refreshed but the location (text only, marker on the map is on the right place) not.

@mrdanleey do you mean the location data shown at the bottom of the screen?

**Comment by mrdanleey** [comment] 2023-07-19 19:59
> That's great to hear! 
> 
> > One thing I notice is that when I'm on the map and clicking the first phone I'm following and than clicking on the 2nd phone I'm following the name refreshed but the location (text only, marker on the map is on the right place) not.
> 
> @mrdanleey do you mean the location data shown at the bottom of the screen?

Yes that's what I mean

**Comment by Myzel394** [comment] 2023-07-20 16:01
Closing this as it's completed now. @mrdanleey I'm not able to reproduce your issue unfortunately. Could you open another issue with more details?

**Closed by Myzel394** 2023-07-20 16:01 UTC
Labels: bug

**Comment by mrdanleey** [comment] 2023-07-28 23:28
I open this bug again becouse after installing the newest version the bug is back. I do not recieve updates while the app is in the background
