### ISSUE TITLE
[BUG] v0.15.0 — black screen when launching application

### ISSUE THREAD

**Issue by Korb** [Myzel394/locus#124] opened 2023-10-01 09:18 UTC
## OS

* [X] Android
* [ ] iOS

## Android specific
If you ticked `Android`, please specify on which Android flavor this issue happens

* [ ] Samsung Android (Samsung Phones)
* [ ] MIUI (Xiaomi Phones)
* [ ] Stock ROM (Google Phones)
* [ ] Huawei Android (Huawei Phones)
* [ ] GrapheneOS
  * [ ] I do have Google Play Services installed
* [ ] LineageOS
* [X] Funtouch OS

## To Reproduce
1. Install
2. Run it
3. Watch the black screen as long as you want

## Screenshots
![Screenshot_20231001_112504](https://github.com/Myzel394/locus/assets/3509797/28f36e74-ecf5-4828-a766-72a8bf15f921)

## Additional context
OS version: Funtouch OS 13 Global
Model: V2153 (T1 4G)
Hardware version: MP_0.1
Build number: PD2201OF_EX_A_13.1.15.8.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.120
Kernel version: 4.19.157-perf+. 1 Mon Sep 4 13:23:15 CST 2023
Compile time: 4 Sept 2023 08:11:57
Android security update: 1 September 2023
Google Play system update: 1 August 2023

## Priority
* [ ] Low
* [ ] Medium
* [ ] High
* [X] Urgent
 
## App Version
[locus-arm64-gms.apk](https://github.com/Myzel394/locus/releases/download/v0.15.0/locus-arm64-gms.apk)
 
## Logs
There is no option to enable log creation due to the inability to launch the application.

**Comment by Myzel394** [comment] 2023-10-01 09:55
Hmm, I'm not able to reproduce this issue at the moment. Will take a closer look later.

**Comment by Myzel394** [comment] 2023-10-02 13:11
Did you install this as an **update** (aka you already had Locus installed) or did you install it freshly?

**Comment by Korb** [comment] 2023-10-02 17:56
@Myzel394, update from v0.14.3 locus-arm64-gms.apk or  locus-universal-gms.apk.

As I understand it, until the Google Play-version is released, the application will not provide the ability to cloud synchronize application settings? This is the only thing stopping me from clean installing the current version (not wanting to re-exchange links).

**Comment by Myzel394** [comment] 2023-10-02 18:14
> As I understand it, until the Google Play-version is released, the application will not provide the ability to cloud synchronize application settings

I've never planned to add settings sync, but that's actually a good idea! 

> update from v0.14.3 locus-arm64-gms.apk

Okay I'll take a closer look on that, thanks for your help

**Comment by mrdanleey** [comment] 2023-10-03 19:50
I had the same black screen. After that I removed the app and installed it again and now it works.

Could also not import the exported settings. Got unexpected error.

**Comment by Myzel394** [comment] 2023-10-03 20:21
Found the bug, should be fixed in the next release (will publish soon)

**Closed** 2023-10-03 20:46 UTC
Labels: bug
