### ISSUE TITLE
[FEATURE] Make option to use only app to app, without web. (Add support for deep links)

### ISSUE THREAD

**Issue by Openwrtfunboy** [Myzel394/locus#58] opened 2023-06-11 12:26 UTC
It is impossible to trust an unknown site whose source code is easy to fake. The problem is not only the site locus.cfd, but any site in general.

For complete privacy and security, it would be a good idea to avoid using the site, and use the scheme of that you can see through the application geo of another user, not only share. And as a fallback already use the link. Those suggest to the user: share with the user who has the app (maximum security) or just share the link (high security)

Initially, when installing the application, I thought that this would be the case. But you have to trust the site, which saddened me personally.

WEB is not reliable.

**Comment by Myzel394** [comment] 2023-06-11 12:39
Hey @Openwrtfunboy, I'm sorry but I don't quite understand your comment.

When you share a link with another user who has Locus installed, the app will open without touching locus.cfd ever. If you share the link, but the user does not have Locus installed, it will open the website, and (in future) show the location there, if they are on PC, and if they are on mobile, it will ask the user to download the app.

> For complete privacy and security, it would be a good idea to avoid using the site, and use the scheme of that you can see through the application geo of another user, not only share

I'm not sure what you mean by "scheme" - do you mean deep linking such as "locus://blabla_data_here"?

**Comment by Openwrtfunboy** [comment] 2023-06-11 17:42
do you mean deep linking such as "locus://blabla_data_here"?

Yes.

The app should also ask what link the user wants to send WITH THEIR location:
locus:// only for app
or web

Also i think site should not ask to download any app. Geopositon should be showed as fast as possible, cause in emergency case there is not time to find no or accidently click to install and loose time. As well scheme with link with key + file is bad. I cant even test app, because its not want to give me file, but as i understands so first of all i need to share link and then share file.

**Comment by Openwrtfunboy** [comment] 2023-06-11 17:45
It would also be a good idea if the app/site prompts you to give location permission to see how far away the user (which shares geolocation) is

**Comment by Myzel394** [comment] 2023-06-11 17:50
> do you mean deep linking such as "locus://blabla_data_here"?
Yes.

I was thinking about that, but the problem is when someone doesn't have Locus installed, they have no idea on how to open the app :/

>  im using floss version and i cant even test app, because its not want to give me file, but as i understands so first of all i need to share link and then share file.

You either share the file or a link, you don't need both :D I'm currently investigating the problem with files not being shared, see #57 for more.

> It would also be a good idea if the app/site prompts you to give location permission to see how far away the user (which shares geolocation) is

You mean when someone imports a location, they should be able to see how far away the user is? That's a good idea, I'll add that! :D

**Comment by Openwrtfunboy** [comment] 2023-06-11 17:54
Also think about add integration with panic button such as Ripple. Would be useful.

**Comment by Openwrtfunboy** [comment] 2023-06-11 17:57
And about link. Just give user right to what type of link share. Just in case if server will be infected, who cares much about privacy and use only internal links, should not be affected.

**Comment by Myzel394** [comment] 2023-06-11 17:58
Yes I was already thinking about how to implement that. Maybe one could define some emergency contacts and once panic mode is enabled, it will automatically share the location and send a link to those contacts. And panic mode can be enabled by shaking your device on the main screen - what do you think about this?

> Also think about add integration with panic button such as Ripple. Would be useful

What is Ripple? Can you send me a link?

> And about link. Just give user right to what type of link share. Just in case if server will be infected, who cares much about privacy and use only internal links, should not be affected.

That sounds like a good trade-off

**Comment by Openwrtfunboy** [comment] 2023-06-11 18:04
Hm. Don't think that this is good idea. Better to combinate this with press 5 times on power button. Android will call to emergency contact and at the same time app will engage and start share location.

Ripple:
https://f-droid.org/packages/info.guardianproject.ripple/

**Comment by Myzel394** [comment] 2023-06-11 18:07
> Hm. Don't think that this is good idea. Better to combinate this with press 5 times on power button. Android will call to emergency contact and at the same time app will engage and start share location.

I'm not an Android dev, but is this even possible for an app? If yes, it'd surely be much more convenient to do it this way! :D

Also thanks for the link

**Comment by Openwrtfunboy** [comment] 2023-06-11 18:10
I don't know, but I'm sure this possible if app will be enabled in special abilities. Sorry for English, don't know how it called correctly on eng.

**Comment by Myzel394** [comment] 2023-06-12 06:43
btw @Openwrtfunboy, you do not need the website at all, not even now. If you open Locus and scroll down, you can import the link without having to tap on it. The website itself is just required if you want to **tap** on the link.

**Comment by dhammel** [comment] 2023-06-29 23:05
@Myzel394 

< You either share the file or a link, you don't need both :D I'm currently investigating the problem with files not being shared, see #57 for more.

When I share link, and open in browser it ask to choose file and submit. When choose the viewkey and pressing submit then it displays location just fine.

Is it supposed to work with only the link? Maybe a bug if so

**Comment by Myzel394** [comment] 2023-07-06 19:58
@dhammel There was an issue with links. Could you try again sharing a link and opening it in the browser? It should work now.

**Comment by dhammel** [comment] 2023-07-06 21:50
@Myzel394 

I test v0.11.1 Universal FLOSS build and the link appears working in browser now, however the location doesn't fetch. Verify location test in settings was successful after 2 minutes, but location juat never updates.

Short screen recording: https://drive.proton.me/urls/3EHPR11SHR#LcWjRBEws4Zy

**Comment by Myzel394** [comment] 2023-07-07 07:04
@dhammel could you share your logs? (all the way down on the settings page)

**Comment by dhammel** [comment] 2023-07-07 11:43
@Myzel394

Log Zip file: https://drive.proton.me/urls/HXQMR5HDG4#rOH_AjFqlv-O

For some reason, locus appears working now. Location seems to fetch properly, I don't know what would have caused this though.

**Comment by Myzel394** [comment] 2023-07-07 19:52
@Openwrtfunboy I will close this as there seems to be no more activity here. Feel free to reopen it. Please note that the website is not required though. You can just share the link inside in the app and someone else can import it inside the app without touching the site ever. All the required data is encoded into the URL, meaning that even if the website was down or hacked, that would make no difference since Locus only needs the URL (and the Nostr relays, but since locations completely depend on them, we can also assume it's safe to trust them for sharing the location key).

**Closed by Myzel394** 2023-07-07 19:52 UTC
Labels: enhancement
